### ISSUE TITLE
Prettier's HTML parser fails on `param` tags

### ISSUE THREAD

**Issue by piousdeer** [siefkenj/relax-ng-to-typescript#1]
Thank you for your work. Running the script on [this file](https://github.com/GNOME/gtksourceview/blob/052aac9772ef2e76f4ea9d9f2c27fa0d806254ab/data/language-specs/language2.rng) results in `SyntaxError: Void elements do not have end tags "param"`. Prettier thinks `param` is the HTML param element, which cannot have a closing tag. Switching the parser from `html` to `babel` in generate-typescript.ts seems to fix the problem.

**Comment by siefkenj** [comment]
Interesting issue. Switching to `babel` seems appropriate. Would you be able to make a PR for this change?

**Comment by piousdeer** [comment]
Sure. Now that I think about it, since since Babel parses it as JSX and not as XML, it might also not work in some cases. Thankfully, there's an official XML plugin for Prettier.
